language: node_js
node_js:
    - "0.12"
script: karma start my.conf.js --single-run
before_install:
    - ./.travis/scripts/install_chrome.sh
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
